name: Test and PRINT Modal Authentication
on: [push]

jobs:
  print_modal_authentication:
    name: Print Modal Authentication
    runs-on: ubuntu-latest
    
    steps:
    - name: Safe Debug - Check Secret Existence
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      run: |
        echo "Checking if secrets are set..."
        
        if [ -z "$MODAL_TOKEN_ID" ]; then
          echo "❌ MODAL_TOKEN_ID is NOT set"
        else
          echo "✅ MODAL_TOKEN_ID is set"
          echo "Token ID starts with: ${MODAL_TOKEN_ID:0:3}..."
          echo "Token ID length: ${#MODAL_TOKEN_ID}"
        fi
        
        if [ -z "$MODAL_TOKEN_SECRET" ]; then
          echo "❌ MODAL_TOKEN_SECRET is NOT set"
        else
          echo "✅ MODAL_TOKEN_SECRET is set"
          echo "Token Secret starts with: ${MODAL_TOKEN_SECRET:0:3}..."
          echo "Token Secret length: ${#MODAL_TOKEN_SECRET}"
        fi
        
    - name: Test Modal Authentication
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      run: |
        pip install modal
        echo "Attempting to authenticate with Modal..."
        modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
        echo "Authentication successful!"
        modal app list