name: Test Modal Authentication
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Modal Auth
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      run: |
        pip install modal
        modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
        modal app list